"""Made password nullable

Revision ID: 23be4615053f
Revises: 34513537d9f6
Create Date: 2015-04-24 17:34:35.758506

"""

# revision identifiers, used by Alembic.
revision = '23be4615053f'
down_revision = '34513537d9f6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###
