"""library initial models

Revision ID: 31c6b9835373
Revises: 23be4615053f
Create Date: 2016-01-03 17:32:28.814509

"""

# revision identifiers, used by Alembic.
revision = '31c6b9835373'
down_revision = '23be4615053f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('isDeadTree', sa.Boolean(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('bookType', sa.String(length=64), nullable=False),
    sa.Column('publicationDate', sa.DateTime(), nullable=True),
    sa.Column('originalPublicationDate', sa.DateTime(), nullable=True),
    sa.Column('isbn', sa.String(length=10), nullable=True),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn'),
    sa.UniqueConstraint('isbn13'),
    sa.UniqueConstraint('title')
    )
    op.create_table('authors_to_books',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['library_authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors_to_books')
    op.drop_table('books')
    op.drop_table('publishers')
    op.drop_table('library_authors')
    ### end Alembic commands ###
