"""Removed unique from category

Revision ID: 377e232604cb
Revises: 21fc43279677
Create Date: 2015-04-18 23:25:41.284636

"""

# revision identifiers, used by Alembic.
revision = '377e232604cb'
down_revision = '21fc43279677'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'category', 'articles', type='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'category', 'articles', ['category'])
    ### end Alembic commands ###
