"""added tag class and authors for articles

Revision ID: e858316343a
Revises: 45a0a3eb7c8a
Create Date: 2015-04-04 15:54:27.021000

"""

# revision identifiers, used by Alembic.
revision = 'e858316343a'
down_revision = '45a0a3eb7c8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('authors',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('articles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articles_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('articles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articles_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('authors')
    op.drop_table('tag')
    ### end Alembic commands ###
